<?php
/**
 * Created by PhpStorm.
 * User: Martin
 * Date: 19/11/2018
 * Time: 10:19
 */


namespace App\Model\Table;

use Cake\ORM\Table;

class PicturesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->belongsTo('Author');
        $this->hasMany('Comment');
    }

}